guiSetInputMode("no_binds_when_editing")

addEventHandler("onClientResourceStart", resourceRoot,
    function()
        local screenW, screenH = guiGetScreenSize()
        banMain = guiCreateWindow((screenW - 602) / 2, (screenH - 461) / 2, 602, 461, " Ban Logs", false)
        guiWindowSetSizable(banMain, false)
        guiSetVisible(banMain, false)

        gridListBans = guiCreateGridList(9, 22, 583, 312, false, banMain)
        guiGridListAddColumn(gridListBans, "Serial", 0.4)
        guiGridListAddColumn(gridListBans, "Razon", 0.2)
        guiGridListAddColumn(gridListBans, "Tiempo de Ban", 0.2)
        guiGridListAddColumn(gridListBans, "Admin", 0.2)
        variableRazon = guiCreateEdit(9, 357, 296, 31, "", false, banMain)
        variableSerial = guiCreateEdit(9, 406, 296, 31, "", false, banMain)
        buttonAddBan = guiCreateButton(309, 406, 158, 31, "Banear Serial", false, banMain)
        guiSetFont(buttonAddBan, "default-bold-small")
        guiSetProperty(buttonAddBan, "NormalTextColour", "FFAAAAAA")
        buttonRemoveBan = guiCreateButton(465, 406, 127, 31, "Remover Ban", false, banMain)
        guiSetFont(buttonRemoveBan, "default-bold-small")
        guiSetProperty(buttonRemoveBan, "NormalTextColour", "FFAAAAAA")
        variableTiempo = guiCreateEdit(311, 357, 281, 31, "", false, banMain)
        guiLabel1 = guiCreateLabel(9, 334, 296, 23, "Razon", false, banMain)
        guiSetFont(guiLabel1, "default-bold-small")
        guiLabelSetHorizontalAlign(guiLabel1, "center", false)
        guiLabelSetVerticalAlign(guiLabel1, "center")
        guiLabel3 = guiCreateLabel(311, 334, 281, 23, "Tiempo (0 = Ban Permanente)", false, banMain)
        guiSetFont(guiLabel3, "default-bold-small")
        guiLabelSetHorizontalAlign(guiLabel3, "center", false)
        guiLabelSetVerticalAlign(guiLabel3, "center")
        guiLabel2 = guiCreateLabel(10, 388, 291, 18, "Serial", false, banMain)
        guiSetFont(guiLabel2, "default-bold-small")
        guiLabelSetHorizontalAlign(guiLabel2, "center", false)
        guiLabelSetVerticalAlign(guiLabel2, "center")    
    end
)