function buttonsGeneral()
    local adminLevel = getElementData(localPlayer, "Occupation")
    if (adminLevel == "New Staff") then
        guiSetProperty(buttonPunish, "Disabled", "False")
        guiSetProperty(buttonWarp, "Disabled", "False")
        guiSetProperty(buttonWarpTo, "Disabled", "False")
        guiSetProperty(buttonRename, "Disabled", "True")
        guiSetProperty(buttonFreeze, "Disabled", "False")
        guiSetProperty(buttonGetAmmo, "Disabled", "True")
        guiSetProperty(buttonSpectate, "Disabled", "True")
        guiSetProperty(buttonSlap, "Disabled", "True")
        guiSetProperty(buttonKillPlayer, "Disabled", "True")
        guiSetProperty(buttonViewPunishlog, "Disabled", "True")
        guiSetProperty(buttonFreezeVeh, "Disabled", "True")
        guiSetProperty(buttonFixVeh, "Disabled", "False")
        guiSetProperty(buttonDestroyVeh, "Disabled", "True")
        guiSetProperty(buttonBlowVeh, "Disabled", "True")
        guiSetProperty(buttonGiveVehicle, "Disabled", "False")
        guiSetProperty(buttonSkin, "Disabled", "False")
        guiSetProperty(buttonCash, "Disabled", "True")
        guiSetProperty(buttonArmor, "Disabled", "True")
        guiSetProperty(buttonBurn, "Disabled", "True")
        guiSetProperty(buttonWarpPoint, "Disabled", "False")
        guiSetProperty(buttonTools, "Disabled", "False")
        guiSetProperty(buttonBanLog, "Disabled", "True")
        guiSetProperty(buttonHealth, "Disabled", "True")
        guiSetProperty(buttonDiscord, "Disabled", "True")
    elseif (adminLevel == "Trained Staff") then
        guiSetProperty(buttonPunish, "Disabled", "False")
        guiSetProperty(buttonWarp, "Disabled", "False")
        guiSetProperty(buttonWarpTo, "Disabled", "False")
        guiSetProperty(buttonRename, "Disabled", "False")
        guiSetProperty(buttonFreeze, "Disabled", "False")
        guiSetProperty(buttonGetAmmo, "Disabled", "True")
        guiSetProperty(buttonSpectate, "Disabled", "False")
        guiSetProperty(buttonSlap, "Disabled", "False")
        guiSetProperty(buttonKillPlayer, "Disabled", "False")
        guiSetProperty(buttonViewPunishlog, "Disabled", "True")
        guiSetProperty(buttonFreezeVeh, "Disabled", "False")
        guiSetProperty(buttonFixVeh, "Disabled", "False")
        guiSetProperty(buttonDestroyVeh, "Disabled", "False")
        guiSetProperty(buttonBlowVeh, "Disabled", "True")
        guiSetProperty(buttonGiveVehicle, "Disabled", "False")
        guiSetProperty(buttonSkin, "Disabled", "False")
        guiSetProperty(buttonCash, "Disabled", "True")
        guiSetProperty(buttonArmor, "Disabled", "True")
        guiSetProperty(buttonBurn, "Disabled", "True")
        guiSetProperty(buttonWarpPoint, "Disabled", "False")
        guiSetProperty(buttonTools, "Disabled", "False")
        guiSetProperty(buttonBanLog, "Disabled", "True")
        guiSetProperty(buttonHealth, "Disabled", "True")
        guiSetProperty(buttonDiscord, "Disabled", "True")
    elseif (adminLevel == "Trusted Staff") then
        guiSetProperty(buttonPunish, "Disabled", "False")
        guiSetProperty(buttonWarp, "Disabled", "False")
        guiSetProperty(buttonWarpTo, "Disabled", "False")
        guiSetProperty(buttonRename, "Disabled", "False")
        guiSetProperty(buttonFreeze, "Disabled", "False")
        guiSetProperty(buttonGetAmmo, "Disabled", "True")
        guiSetProperty(buttonSpectate, "Disabled", "False")
        guiSetProperty(buttonSlap, "Disabled", "False")
        guiSetProperty(buttonKillPlayer, "Disabled", "False")
        guiSetProperty(buttonViewPunishlog, "Disabled", "False")
        guiSetProperty(buttonFreezeVeh, "Disabled", "False")
        guiSetProperty(buttonFixVeh, "Disabled", "False")
        guiSetProperty(buttonDestroyVeh, "Disabled", "False")
        guiSetProperty(buttonBlowVeh, "Disabled", "False")
        guiSetProperty(buttonGiveVehicle, "Disabled", "False")
        guiSetProperty(buttonSkin, "Disabled", "False")
        guiSetProperty(buttonCash, "Disabled", "True")
        guiSetProperty(buttonArmor, "Disabled", "False")
        guiSetProperty(buttonBurn, "Disabled", "False")
        guiSetProperty(buttonWarpPoint, "Disabled", "False")
        guiSetProperty(buttonTools, "Disabled", "False")
        guiSetProperty(buttonBanLog, "Disabled", "True")
        guiSetProperty(buttonHealth, "Disabled", "True")
        guiSetProperty(buttonDiscord, "Disabled", "True")
    elseif (adminLevel == "High Staff") then
        guiSetProperty(buttonPunish, "Disabled", "False")
        guiSetProperty(buttonWarp, "Disabled", "False")
        guiSetProperty(buttonWarpTo, "Disabled", "False")
        guiSetProperty(buttonRename, "Disabled", "False")
        guiSetProperty(buttonFreeze, "Disabled", "False")
        guiSetProperty(buttonGetAmmo, "Disabled", "False")
        guiSetProperty(buttonSpectate, "Disabled", "False")
        guiSetProperty(buttonSlap, "Disabled", "False")
        guiSetProperty(buttonKillPlayer, "Disabled", "False")
        guiSetProperty(buttonViewPunishlog, "Disabled", "False")
        guiSetProperty(buttonFreezeVeh, "Disabled", "False")
        guiSetProperty(buttonFixVeh, "Disabled", "False")
        guiSetProperty(buttonDestroyVeh, "Disabled", "False")
        guiSetProperty(buttonBlowVeh, "Disabled", "False")
        guiSetProperty(buttonGiveVehicle, "Disabled", "False")
        guiSetProperty(buttonSkin, "Disabled", "False")
        guiSetProperty(buttonCash, "Disabled", "True")
        guiSetProperty(buttonArmor, "Disabled", "False")
        guiSetProperty(buttonBurn, "Disabled", "False")
        guiSetProperty(buttonWarpPoint, "Disabled", "False")
        guiSetProperty(buttonTools, "Disabled", "False")
        guiSetProperty(buttonBanLog, "Disabled", "False")
        guiSetProperty(buttonHealth, "Disabled", "False")
        guiSetProperty(buttonDiscord, "Disabled", "False")
    elseif (adminLevel == "Head Staff") then
        guiSetProperty(buttonPunish, "Disabled", "False")
        guiSetProperty(buttonWarp, "Disabled", "False")
        guiSetProperty(buttonWarpTo, "Disabled", "False")
        guiSetProperty(buttonRename, "Disabled", "False")
        guiSetProperty(buttonFreeze, "Disabled", "False")
        guiSetProperty(buttonGetAmmo, "Disabled", "False")
        guiSetProperty(buttonSpectate, "Disabled", "False")
        guiSetProperty(buttonSlap, "Disabled", "False")
        guiSetProperty(buttonKillPlayer, "Disabled", "False")
        guiSetProperty(buttonViewPunishlog, "Disabled", "False")
        guiSetProperty(buttonFreezeVeh, "Disabled", "False")
        guiSetProperty(buttonFixVeh, "Disabled", "False")
        guiSetProperty(buttonDestroyVeh, "Disabled", "False")
        guiSetProperty(buttonBlowVeh, "Disabled", "False")
        guiSetProperty(buttonGiveVehicle, "Disabled", "False")
        guiSetProperty(buttonSkin, "Disabled", "False")
        guiSetProperty(buttonCash, "Disabled", "False")
        guiSetProperty(buttonArmor, "Disabled", "False")
        guiSetProperty(buttonBurn, "Disabled", "False")
        guiSetProperty(buttonWarpPoint, "Disabled", "False")
        guiSetProperty(buttonTools, "Disabled", "False")
        guiSetProperty(buttonBanLog, "Disabled", "False")
        guiSetProperty(buttonHealth, "Disabled", "False")
        guiSetProperty(buttonDiscord, "Disabled", "False")
    end
end

function buttonsPunish()
    local adminLevel = getElementData(localPlayer, "Occupation")
    if (adminLevel == "New Staff") then
        guiSetProperty(buttonMute, "Disabled", "False")
        guiSetProperty(buttonKick, "Disabled", "True")
        guiSetProperty(buttonJail, "Disabled", "True")
        guiSetProperty(buttonBan, "Disabled", "True")
        guiSetProperty(buttonReconnect, "Disabled", "True")
        guiSetProperty(buttonRemoveAccount, "Disabled", "True")
    elseif (adminLevel == "Trained Staff") then
        guiSetProperty(buttonMute, "Disabled", "False")
        guiSetProperty(buttonKick, "Disabled", "False")
        guiSetProperty(buttonJail, "Disabled", "False")
        guiSetProperty(buttonBan, "Disabled", "True")
        guiSetProperty(buttonReconnect, "Disabled", "False")
        guiSetProperty(buttonRemoveAccount, "Disabled", "True")
    elseif (adminLevel == "Trusted Staff") then
        guiSetProperty(buttonMute, "Disabled", "False")
        guiSetProperty(buttonKick, "Disabled", "False")
        guiSetProperty(buttonJail, "Disabled", "False")
        guiSetProperty(buttonBan, "Disabled", "False")
        guiSetProperty(buttonReconnect, "Disabled", "False")
        guiSetProperty(buttonRemoveAccount, "Disabled", "True")
    elseif (adminLevel == "High Staff") then
        guiSetProperty(buttonMute, "Disabled", "False")
        guiSetProperty(buttonKick, "Disabled", "False")
        guiSetProperty(buttonJail, "Disabled", "False")
        guiSetProperty(buttonBan, "Disabled", "False")
        guiSetProperty(buttonReconnect, "Disabled", "False")
        guiSetProperty(buttonRemoveAccount, "Disabled", "True")
    elseif (adminLevel == "Head Staff") then
        guiSetProperty(buttonMute, "Disabled", "False")
        guiSetProperty(buttonKick, "Disabled", "False")
        guiSetProperty(buttonJail, "Disabled", "False")
        guiSetProperty(buttonBan, "Disabled", "False")
        guiSetProperty(buttonReconnect, "Disabled", "False")
        guiSetProperty(buttonRemoveAccount, "Disabled", "False")
    end
end